<div style="text-align: center;"><h1 style="margin-bottom: 10px; font-weight: bold;">DATA PROFILING CLEANING</h1></div>

## IMPORT DATASETS

In [1]:
import pandas as pd
employee_survey = pd.read_csv('../data/raw/employee_survey_data.csv')
general_data = pd.read_csv('../data/raw/general_data.csv')
manager_survey = pd.read_csv('../data/raw/manager_survey_data.csv')

# Column names of each dataset
print("--- EMPLOYEE SURVEY COLUMNS ---")
print(employee_survey.columns.tolist())

print("\n--- GENERAL DATA COLUMNS ---")
print(general_data.columns.tolist())

print("\n--- MANAGER SURVEY COLUMNS ---")
print(manager_survey.columns.tolist())

--- EMPLOYEE SURVEY COLUMNS ---
['EmployeeID', 'EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance']

--- GENERAL DATA COLUMNS ---
['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender', 'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome', 'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

--- MANAGER SURVEY COLUMNS ---
['EmployeeID', 'JobInvolvement', 'PerformanceRating']

## general_data TABLE CLEANING

In [3]:
# Data structure and first few rows
print("--- GENERAL DATA PREVIEW ---")
display(general_data.head())

# Column types and missing values
print("\n--- GENERAL DATA INFO ---")
general_data.info()

# Statistical summary
print("\n--- GENERAL DATA SUMMARY ---")
display(general_data.describe())

--- GENERAL DATA PREVIEW ---

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

--- GENERAL DATA INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      4410 non-null   int64
 1   Attrition                4410 non-null   str
 2   BusinessTravel           4410 non-null   str
 3   Department               4410 non-null   str
 4   DistanceFromHome         4410 non-null   int64
 5   Education                4410 non-null   int64
 6   EducationField           4410 non-null   str
 7   EmployeeCount            4410 non-null   int64
 8   EmployeeID               4410 non-null   int64
 9   Gender                   4410 non-null   str
 10  JobLevel                 4410 non-null   int64
 11  JobRole                  4410 non-null   str
 12  MaritalStatus            4410 non-null   str
 13  MonthlyIncome            4410 non-null   int64
 14  NumCompaniesWorked       4391 non-null   float64
 15  Over18                   4410 non-null   str
 16  PercentSalaryHike        4410 non-null   int64
 17  StandardHours            4410 non-null   int64
 18  StockOptionLevel         4410 non-null   int64
 19  TotalWorkingYears        4401 non-null   float64
 20  TrainingTimesLastYear    4410 non-null   int64
 21  YearsAtCompany           4410 non-null   int64
 22  YearsSinceLastPromotion  4410 non-null   int64
 23  YearsWithCurrManager     4410 non-null   int64
dtypes: float64(2), int64(14), str(8)
memory usage: 827.0 KB

--- GENERAL DATA SUMMARY ---

,Age,DistanceFromHome,Education,EmployeeCount,EmployeeID,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
count,4410.000000,4410.000000,4410.000000,4410.0,4410.000000,4410.000000,4410.000000,4391.000000,4410.000000,4410.0,4410.000000,4401.000000,4410.000000,4410.000000,4410.000000,4410.000000
mean,36.923810,9.192517,2.912925,1.0,2205.500000,2.063946,65029.312925,2.694830,15.209524,8.0,0.793878,11.279936,2.799320,7.008163,2.187755,4.123129
std,9.133301,8.105026,1.023933,0.0,1273.201673,1.106689,47068.888559,2.498887,3.659108,0.0,0.851883,7.782222,1.288978,6.125135,3.221699,3.567327
min,18.000000,1.000000,1.000000,1.0,1.000000,1.000000,10090.000000,0.000000,11.000000,8.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,2.000000,2.000000,1.0,1103.250000,1.000000,29110.000000,1.000000,12.000000,8.0,0.000000,6.000000,2.000000,3.000000,0.000000,2.000000
50%,36.000000,7.000000,3.000000,1.0,2205.500000,2.000000,49190.000000,2.000000,14.000000,8.0,1.000000,10.000000,3.000000,5.000000,1.000000,3.000000
75%,43.000000,14.000000,4.000000,1.0,3307.750000,3.000000,83800.000000,4.000000,18.000000,8.0,1.000000,15.000000,3.000000,9.000000,3.000000,7.000000
max,60.000000,29.000000,5.000000,1.0,4410.000000,5.000000,199990.000000,9.000000,25.000000,8.0,3.000000,40.000000,6.000000,40.000000,15.000000,17.000000

Above result shows NumCompaniesWorked and TotalWorkingYears columns have missing values.
Some columns are maybe useless for analysis.

### Cross check unique values for suspected useless columns

In [4]:
print(f"Unique values in EmployeeCount: {general_data['EmployeeCount'].unique()}")
print(f"Unique values in Over18: {general_data['Over18'].unique()}")
print(f"Unique values in StandardHours: {general_data['StandardHours'].unique()}")

Unique values in EmployeeCount: [1]
Unique values in Over18: <StringArray>
['Y']
Length: 1, dtype: str
Unique values in StandardHours: [8]

### Drop useless columns

In [5]:
columns_to_drop = ['EmployeeCount', 'Over18', 'StandardHours']
general_data = general_data.drop(columns=columns_to_drop)
print("New shape of general_data:", general_data.shape)

New shape of general_data: (4410, 21)

### Handle missing values

In [6]:
# Fill missing TotalWorkingYears using the median of the employee's exact Age
general_data['TotalWorkingYears'] = general_data.groupby('Age')['TotalWorkingYears'].transform(lambda x: x.fillna(x.median()))

# Fill missing NumCompaniesWorked using the median of the employee's exact Age
general_data['NumCompaniesWorked'] = general_data.groupby('Age')['NumCompaniesWorked'].transform(lambda x: x.fillna(x.median()))

# Check if there are any remaining missing values in general_data
print("Remaining missing values in general_data:")
print(general_data[['TotalWorkingYears', 'NumCompaniesWorked']].isnull().sum())

Remaining missing values in general_data:
TotalWorkingYears     0
NumCompaniesWorked    0
dtype: int64

## employee_survey TABLE CLEANING

In [7]:
print("--- Employee Survey PREVIEW ---")
display(employee_survey.head())

# Column types and missing values
print("\n--- Employee Survey INFO ---")
employee_survey.info()

# Value counts for the Employee Survey columns
print("--- EMPLOYEE SURVEY RATINGS BREAKDOWN ---")
for col in ['EnvironmentSatisfaction', 'JobSatisfaction', 'WorkLifeBalance']:
    print(f"\nValue Counts for {col}:")
    print(employee_survey[col].value_counts().sort_index())

--- Employee Survey PREVIEW ---

   EmployeeID  EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance
0           1                      3.0              4.0              2.0
1           2                      3.0              2.0              4.0
2           3                      2.0              2.0              1.0
3           4                      4.0              4.0              3.0
4           5                      4.0              1.0              3.0

--- Employee Survey INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeID               4410 non-null   int64
 1   EnvironmentSatisfaction  4385 non-null   float64
 2   JobSatisfaction          4390 non-null   float64
 3   WorkLifeBalance          4372 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 137.9 KB
--- EMPLOYEE SURVEY RATINGS BREAKDOWN ---

Value Counts for EnvironmentSatisfaction:
EnvironmentSatisfaction
1.0     845
2.0     856
3.0    1350
4.0    1334
Name: count, dtype: int64

Value Counts for JobSatisfaction:
JobSatisfaction
1.0     860
2.0     840
3.0    1323
4.0    1367
Name: count, dtype: int64

Value Counts for WorkLifeBalance:
WorkLifeBalance
1.0     239
2.0    1019
3.0    2660
4.0     454
Name: count, dtype: int64

Above result shows 3 columns have missing values
### Handle missing values

In [8]:
# Fill missing survey values with their respective column medians
employee_survey['EnvironmentSatisfaction'] = employee_survey['EnvironmentSatisfaction'].fillna(employee_survey['EnvironmentSatisfaction'].median())
employee_survey['JobSatisfaction'] = employee_survey['JobSatisfaction'].fillna(employee_survey['JobSatisfaction'].median())
employee_survey['WorkLifeBalance'] = employee_survey['WorkLifeBalance'].fillna(employee_survey['WorkLifeBalance'].median())

# Verify that there are zero missing values left
print("Remaining missing values in employee_survey:")
print(employee_survey.isnull().sum())

Remaining missing values in employee_survey:
EmployeeID                 0
EnvironmentSatisfaction    0
JobSatisfaction            0
WorkLifeBalance            0
dtype: int64

## manager_survey TABLE

In [9]:
# 1. See the actual data structure and first few rows
print("--- Manager Survey PREVIEW ---")
display(manager_survey.head())

# 2. Check column types and look for missing (null) values
print("\n--- MANAGER Survey INFO ---")
manager_survey.info()

# Check the value counts for the Manager Survey columns
print("\n--- MANAGER SURVEY RATINGS BREAKDOWN ---")
for col in ['JobInvolvement', 'PerformanceRating']:
    print(f"\nValue Counts for {col}:")
    print(manager_survey[col].value_counts().sort_index())

--- Manager Survey PREVIEW ---

   EmployeeID  JobInvolvement  PerformanceRating
0           1               3                  3
1           2               2                  4
2           3               3                  3
3           4               2                  3
4           5               3                  3

--- MANAGER Survey INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         4410 non-null   int64
 1   JobInvolvement     4410 non-null   int64
 2   PerformanceRating  4410 non-null   int64
dtypes: int64(3)
memory usage: 103.5 KB

--- MANAGER SURVEY RATINGS BREAKDOWN ---

Value Counts for JobInvolvement:
JobInvolvement
1     249
2    1125
3    2604
4     432
Name: count, dtype: int64

Value Counts for PerformanceRating:
PerformanceRating
3    3732
4     678
Name: count, dtype: int64

This table is already clean
## MERGE TABLES

In [10]:
# Merge all three cleaned dataframes together on EmployeeID
merged_df = general_data.merge(employee_survey, on='EmployeeID', how='inner')
final_df = merged_df.merge(manager_survey, on='EmployeeID', how='inner')

expected_rows = 4410
actual_rows = final_df.shape[0]
duplicate_ids = final_df.duplicated(subset=['EmployeeID']).sum()

# Validation check
assert final_df.shape[0] == 4410, f"Wrong row count: {final_df.shape[0]}"
assert final_df['EmployeeID'].is_unique, "Duplicate employees found!"
assert final_df.shape[0] == general_data.shape[0], "Row multiplication detected!"

print("All checks passed perfectly!")

All checks passed perfectly!

## SAVE THE FILE

In [12]:
final_df.to_csv('../data/processed/hr_employee_master.csv', index=False)
print("\nFile saved successfully as 'hr_employee_master.csv'.")

File saved successfully as 'hr_employee_master.csv'.

## FINAL VALIDATION FOR FUTURE ANALYSIS

In [15]:
print("Shape:", final_df.shape)

print("\nDuplicate rows:", final_df.duplicated().sum())
print("Duplicate EmployeeID:", final_df["EmployeeID"].duplicated().sum())

print("\nMissing values:")
print(final_df.isna().sum()[final_df.isna().sum() > 0])

print("\nAttrition:")
print(final_df["Attrition"].value_counts())

print("\nConstant columns:")
print(final_df.columns[final_df.nunique() <= 1].tolist())

Shape: (4410, 26)

Duplicate rows: 0
Duplicate EmployeeID: 0

Missing values:
Series([], dtype: int64)

Attrition:
Attrition
No     3699
Yes     711
Name: count, dtype: int64

Constant columns:
[]